In [1]:

import sys
from sklearn import preprocessing
from tensorflow import keras
from sklearn.model_selection import train_test_split
sys.path.append('../')
from app.preprocessing.diabetes import Diabetes
import numpy as np

In [2]:
import tensorflow as tf

In [3]:
%load_ext autoreload
%autoreload 2

Read dataset

In [5]:
diab = Diabetes()
diab.read()

c:\Users\Ryadh\Desktop\paris\projet_clean\DE_project_M2\notebook\..\app\preprocessing\diabetes.py:87: ParserWarning: Both a converter and dtype were specified for column chol_hdl_ratio - only the converter will be used.
  pd.read_csv(
c:\Users\Ryadh\Desktop\paris\projet_clean\DE_project_M2\notebook\..\app\preprocessing\diabetes.py:87: ParserWarning: Both a converter and dtype were specified for column bmi - only the converter will be used.
  pd.read_csv(
c:\Users\Ryadh\Desktop\paris\projet_clean\DE_project_M2\notebook\..\app\preprocessing\diabetes.py:87: ParserWarning: Both a converter and dtype were specified for column waist_hip_ratio - only the converter will be used.
  pd.read_csv(

Preprocess dataset

In [6]:
diab.preprocess(rm_duplicates = True, normalize= False)
diab.df

,cholesterol_level,glucose_level,hdl_cholesterol,cholesterol_hdl_ratio,age,gender,height,weight,body_mass_idx,systolic_blood_pressure,diastolic_blood_pressure,waist_size,hip_size,waist_hip_size_ratio,diabetes
0,193,77,49,3.9,19,0,61,119,22.500000,118,70,32,38,0.84,0
1,146,79,41,3.6,19,0,60,135,26.400000,108,58,33,40,0.83,0
2,217,75,54,4.0,20,0,67,187,29.299999,110,72,40,45,0.89,0
3,226,97,70,3.2,20,0,64,114,19.600000,122,64,31,39,0.79,0
4,164,91,67,2.4,20,0,70,141,20.200001,122,86,32,39,0.82,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,227,105,44,5.2,83,0,59,125,25.200001,150,90,35,40,0.88,0
386,226,279,52,4.3,84,0,60,192,37.500000,144,88,41,48,0.85,1
387,301,90,118,2.6,89,0,61,115,21.700001,218,90,31,41,0.76,0
388,232,184,114,2.0,91,0,61,127,24.000000,170,82,35,38,0.92,1
389,165,94,69,2.4,92,0,62,217,39.700001,160,82,51,51,1.00,0